# Generated by Django 5.2.12 on 2026-03-30 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academics.department"
            ),
        ),
        migrations.AddField(
            model_name="programcourse",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academics.course"
            ),
        ),
        migrations.AddField(
            model_name="programcourse",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academics.program"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academics.program"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="courseenrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academics.student"
            ),
        ),
        migrations.AddField(
            model_name="teachingassignment",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academics.faculty"
            ),
        ),
        migrations.AddField(
            model_name="teachingassignment",
            name="offering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.courseoffering",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("enrollment", "date"), name="unique_attendance"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseoffering",
            constraint=models.UniqueConstraint(
                fields=("course", "semester", "academic_year", "section"),
                name="unique_course_offering",
            ),
        ),
        migrations.AddConstraint(
            model_name="programcourse",
            constraint=models.UniqueConstraint(
                fields=("program", "course"), name="unique_program_course"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseenrollment",
            constraint=models.UniqueConstraint(
                fields=("student", "offering"), name="unique_student_offering"
            ),
        ),
        migrations.AddConstraint(
            model_name="teachingassignment",
            constraint=models.UniqueConstraint(
                fields=("faculty", "offering"), name="unique_faculty_offering"
            ),
        ),
    ]
